### ISSUE TITLE
Error adding persistence

### ISSUE THREAD

**Issue by cmreigrut** [alexa/skill-sample-nodejs-first-skill#23]
I get the following error when I try to add the persistence to my functioning code from Module 4.
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/index.js:5:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Adding the persistence line to the package.json file works fine, but seems to have no effect.  Once I then add the very first line that references it 
   const persistenceAdapter = require('ask-sdk-s3-persistence-adapter');
in the index.js file causes the error to occur.

**Comment by cmreigrut** [comment]
Apparently it was only a transient issue
